# OBTAIN STAGE

In [1]:
import os
import zipfile
import pandas as pd
from tqdm import tqdm

In [3]:
# List the zip's contents without extracting anything yet
zip_path = "../data/raw/FakeAVCeleb_v1.2.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    all_files = zip_ref.namelist()

print(f"Total files in zip: {len(all_files)}")
print("\nFirst 20 entries:")
for f in all_files[:20]:
    print(" -", f)

Total files in zip: 24110

First 20 entries:
 - FakeAVCeleb_v1.2/
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_10_id00476_wavtolip.mp4
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_10_id01076_wavtolip.mp4
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_10_id01179_wavtolip.mp4
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_10_id02005_wavtolip.mp4
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_10_id02342_wavtolip.mp4
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_12_id00518_wavtolip.mp4
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_12_id00761_wavtolip.mp4
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_12_id00987_wavtolip.mp4
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_12_id01856_wavtolip.mp4
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_12_id02296_wavtolip.mp4
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_2_id00166_wavtolip.mp4
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_2_id00701_wavtolip.mp4
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_2_id01236_wavtolip.mp4
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_2_id01521_wavtolip.mp4
 - FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_2_id01598_wavtolip.mp4

In [4]:
# Search for any CSV/metadata files
meta_candidates = [f for f in all_files if f.lower().endswith('.csv') or 'meta' in f.lower()]
print("Metadata candidates found:")
for f in meta_candidates:
    print(" -", f)

# Also inspect the top-level category folders
top_level = sorted(set(f.split('/')[1] for f in all_files if '/' in f and len(f.split('/')) > 1))
print("\nTop-level categories:")
for t in top_level:
    print(" -", t)

Metadata candidates found:
 - FakeAVCeleb_v1.2/meta_data.csv

Top-level categories:
 -
 - FakeVideo-FakeAudio
 - FakeVideo-RealAudio
 - README.txt
 - RealVideo-FakeAudio
 - RealVideo-RealAudio
 - meta_data.csv

In [5]:
#Extract just the metadata CSV and README (tiny, safe)
small_files = ["FakeAVCeleb_v1.2/meta_data.csv", "FakeAVCeleb_v1.2/README.txt"]

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    for f in small_files:
        zip_ref.extract(f, path="../data/raw/")

print("Extracted:", small_files)

Extracted: ['FakeAVCeleb_v1.2/meta_data.csv', 'FakeAVCeleb_v1.2/README.txt']

In [6]:
df = pd.read_csv("../data/raw/FakeAVCeleb_v1.2/meta_data.csv")

print(df.shape)
print(df.columns.tolist())
df.head()

(21566, 10)
['source', 'target1', 'target2', 'method', 'category', 'type', 'race', 'gender', 'path', 'Unnamed: 9']

,source,target1,target2,method,category,type,race,gender,path,Unnamed: 9
0,id00076,-,-,real,A,RealVideo-RealAudio,African,men,00109.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id...
1,id00166,-,-,real,A,RealVideo-RealAudio,African,men,00010.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id...
2,id00173,-,-,real,A,RealVideo-RealAudio,African,men,00118.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id...
3,id00366,-,-,real,A,RealVideo-RealAudio,African,men,00118.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id...
4,id00391,-,-,real,A,RealVideo-RealAudio,African,men,00052.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id...

In [7]:
# See the full, untruncated content of a few rows, especially the path columns
pd.set_option('display.max_colwidth', None)
print(df[['path', 'Unnamed: 9']].head(10))

# Distribution across type (our main label)
print("\n--- type ---")
print(df['type'].value_counts())

# Distribution across category (short code)
print("\n--- category ---")
print(df['category'].value_counts())

# Distribution across race and gender (relevant for balanced sampling + your Ethics Statement)
print("\n--- race ---")
print(df['race'].value_counts())

print("\n--- gender ---")
print(df['gender'].value_counts())

        path                                           Unnamed: 9
0  00109.mp4  FakeAVCeleb/RealVideo-RealAudio/African/men/id00076
1  00010.mp4  FakeAVCeleb/RealVideo-RealAudio/African/men/id00166
2  00118.mp4  FakeAVCeleb/RealVideo-RealAudio/African/men/id00173
3  00118.mp4  FakeAVCeleb/RealVideo-RealAudio/African/men/id00366
4  00052.mp4  FakeAVCeleb/RealVideo-RealAudio/African/men/id00391
5  00099.mp4  FakeAVCeleb/RealVideo-RealAudio/African/men/id00475
6  00109.mp4  FakeAVCeleb/RealVideo-RealAudio/African/men/id00476
7  00206.mp4  FakeAVCeleb/RealVideo-RealAudio/African/men/id00478
8  00031.mp4  FakeAVCeleb/RealVideo-RealAudio/African/men/id00518
9  00092.mp4  FakeAVCeleb/RealVideo-RealAudio/African/men/id00701

--- type ---
type
FakeVideo-FakeAudio    10857
FakeVideo-RealAudio     9709
RealVideo-RealAudio      500
RealVideo-FakeAudio      500
Name: count, dtype: int64

--- category ---
category
D    10857
C     9709
A      500
B      500
Name: count, dtype: int64

--- race ---
race
Caucasian (American)    4864
Caucasian (European)    4693
Asian (South)           4414
African                 4097
Asian (East)            3498
Name: count, dtype: int64

--- gender ---
gender
men      11107
women    10459
Name: count, dtype: int64

In [8]:
# Build the subset by sampling from the metadata, then matching to real zip filenames
import random
random.seed(42)  # reproducibility — important for your Methodology section

# Take all rows for the two scarce real categories
real_real = df[df['type'] == 'RealVideo-RealAudio']
real_fake_audio = df[df['type'] == 'RealVideo-FakeAudio']

# Sample 500 from each of the two abundant fake categories
fake_real_audio = df[df['type'] == 'FakeVideo-RealAudio'].sample(n=500, random_state=42)
fake_fake_audio = df[df['type'] == 'FakeVideo-FakeAudio'].sample(n=500, random_state=42)

subset_df = pd.concat([real_real, real_fake_audio, fake_real_audio, fake_fake_audio], ignore_index=True)

print(subset_df.shape)
print(subset_df['type'].value_counts())

(2000, 10)
type
RealVideo-RealAudio    500
RealVideo-FakeAudio    500
FakeVideo-RealAudio    500
FakeVideo-FakeAudio    500
Name: count, dtype: int64

In [9]:
# Match each subset row to its actual filename in the zip
def find_zip_path(row, all_files):
    # Build the folder prefix from Unnamed: 9, e.g. "FakeAVCeleb/RealVideo-RealAudio/African/men/id00076"
    folder_prefix = row['Unnamed: 9'].replace('FakeAVCeleb/', 'FakeAVCeleb_v1.2/')
    short_name = row['path'].replace('.mp4', '')  # e.g. "00109"
    
    # Find files in this folder that start with the short name (handles the longer real filenames)
    matches = [f for f in all_files if f.startswith(folder_prefix + '/') and short_name in f and f.endswith('.mp4')]
    return matches[0] if matches else None

subset_df['zip_path'] = subset_df.apply(lambda row: find_zip_path(row, all_files), axis=1)

# Check how many matched successfully
print(f"Matched: {subset_df['zip_path'].notna().sum()} / {len(subset_df)}")
subset_df[['type', 'path', 'Unnamed: 9', 'zip_path']].head(10)

Matched: 2000 / 2000

,type,path,Unnamed: 9,zip_path
0,RealVideo-RealAudio,00109.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id00076,FakeAVCeleb_v1.2/RealVideo-RealAudio/African/men/id00076/00109.mp4
1,RealVideo-RealAudio,00010.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id00166,FakeAVCeleb_v1.2/RealVideo-RealAudio/African/men/id00166/00010.mp4
2,RealVideo-RealAudio,00118.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id00173,FakeAVCeleb_v1.2/RealVideo-RealAudio/African/men/id00173/00118.mp4
3,RealVideo-RealAudio,00118.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id00366,FakeAVCeleb_v1.2/RealVideo-RealAudio/African/men/id00366/00118.mp4
4,RealVideo-RealAudio,00052.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id00391,FakeAVCeleb_v1.2/RealVideo-RealAudio/African/men/id00391/00052.mp4
5,RealVideo-RealAudio,00099.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id00475,FakeAVCeleb_v1.2/RealVideo-RealAudio/African/men/id00475/00099.mp4
6,RealVideo-RealAudio,00109.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id00476,FakeAVCeleb_v1.2/RealVideo-RealAudio/African/men/id00476/00109.mp4
7,RealVideo-RealAudio,00206.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id00478,FakeAVCeleb_v1.2/RealVideo-RealAudio/African/men/id00478/00206.mp4
8,RealVideo-RealAudio,00031.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id00518,FakeAVCeleb_v1.2/RealVideo-RealAudio/African/men/id00518/00031.mp4
9,RealVideo-RealAudio,00092.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id00701,FakeAVCeleb_v1.2/RealVideo-RealAudio/African/men/id00701/00092.mp4

In [10]:
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    total_size = sum(zip_ref.getinfo(f).file_size for f in subset_df['zip_path'])

print(f"Estimated extracted size: {total_size / (1024**3):.2f} GB")

Estimated extracted size: 0.49 GB

In [11]:
extract_root = "../data/raw/"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    for f in tqdm(subset_df['zip_path'], desc="Extracting subset"):
        zip_ref.extract(f, path=extract_root)

print("Extraction complete.")

Extracting subset: 100%|█████████████████████████████████████████████████████████████████████████████████| 2000/2000 [00:05<00:00, 366.88it/s]

Extraction complete.

In [12]:
# Check that every extracted file actually exists on disk
subset_df['local_path'] = subset_df['zip_path'].apply(lambda p: os.path.join(extract_root, p))
missing = subset_df[~subset_df['local_path'].apply(os.path.exists)]

print(f"Successfully extracted: {len(subset_df) - len(missing)} / {len(subset_df)}")
if len(missing) > 0:
    print("Missing files:")
    print(missing[['type', 'zip_path']])

Successfully extracted: 2000 / 2000

In [13]:
subset_df.to_csv("../data/processed/subset_metadata.csv", index=False)
print("Saved subset_metadata.csv")

Saved subset_metadata.csv

# SCRUB STAGE